# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Hit Points and Hijinks
email: contact@hitpointsandhijinks.quest
description: > # this means to ignore newlines until "baseurl:"
  Hit Points and Hijinks Podcast
baseurl: ""
url: "https://hitpointsandhijinks.quest"
github_username:  hpandhijinks
permalink: /:title.html
excerpt_separator: <!--more-->
lang: "en-US"
author: "Hit Points and Hijinks"

# Build settings
markdown: kramdown

exclude:
  - docker-compose.yml

plugins:
  - jekyll-email-protect
